version: '3' 
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: MQTT
    restart: unless-stopped
    env_file:
      - $MOSQUITTO_INSTALL_WORK_DIR/mqtt.env
    ports:
      - "1883:1883"
    volumes:
      - $MOSQUITTO_INSTALL_WORK_DIR/mosquitto-entrypoint.sh:/docker-entrypoint.sh
    entrypoint: ["sh", "/docker-entrypoint.sh"]
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
