version: '3'
services:
  mosquitto:
    env_file:
      - $MOSQUITTO_INSTALL_WORK_DIR/mqtt.env
      - $MOSQUITTO_INSTALL_WORK_DIR/mqtt_bridge.env
    volumes:
      - $MOSQUITTO_INSTALL_WORK_DIR//mosquitto-entrypoint.sh:/docker-entrypoint.sh
      - ${CACERT_FILE}:/etc/ssl/certs/ca-certificates.crt
