version: '3' 
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: MQTT
    restart: unless-stopped
    env_file:
      - mqtt.env
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto-entrypoint.sh:/docker-entrypoint.sh
      - /etc/ssl/certs/:/etc/ssl/certs/
    entrypoint: ["sh", "/docker-entrypoint.sh"]
    command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
